package iisg.nl.hsnmigrate;

public class  Constants {

	public static final String HSN_FIELD_SEPARATOR_ADDRESS     = "/";
	public static final String HSN_FIELD_SEPARATOR_BEVADM      = "&";
	public static final String HSN_FIELD_SEPARATOR_COUNTRY     = "$";
	public static final String HSN_FIELD_SEPARATOR_HAMLET      = "!";
	public static final String HSN_FIELD_SEPARATOR_PATRONIME   = "$";
	public static final String HSN_FIELD_SEPARATOR_PROVINCE    = "%";
	public static final String HSN_FIELD_SEPARATOR_TITLE       = "!";
	public static final String HSN_FIELD_SEPARATOR_VOORVOEG    = ",";

	// Field name position 1 and 2 : source names
	public static final String S_B0 = "B0";                 // Steekproef
	public static final String S_B1 = "B1";                 // Certificates (of birth)
	public static final String S_B2 = "B2";                 // Witnesses
	public static final String S_B3 = "B3";                 // Remarks
	public static final String S_B4 = "B4";                 // Royal decrees
	public static final String S_B5 = "B5";                 // Father
	public static final String S_B6 = "B6";                 // Certificates without details
	public static final String S_D1 = "D1";                 // Certificates (of death)
	public static final String S_D2 = "D2";
	public static final String S_D3 = "D3";
	public static final String S_D4 = "D4";
	public static final String S_MA = "MA";                 // Marriage data key part
	public static final String S_M1 = "M1";
	public static final String S_M2 = "M2";
	public static final String S_M3 = "M3";
	public static final String S_M4 = "M4";
	public static final String S_M5 = "M5";
	public static final String S_M6 = "M6";
	public static final String S_M7 = "M7";

	// Field name position 3 and 4 : role names
	public static final String F_1C = "1C";                 // Marriage announcement code municipality
	public static final String F_1D = "1D";                 // Marriage announcement day
	public static final String F_1L = "1L";                 // Marriage announcement location
	public static final String F_1M = "1M";                 // Marriage announcement month
	public static final String F_1Y = "1Y";                 // Marriage announcement year
	public static final String F_2C = "2C";                 // Marriage announcement code municipality
	public static final String F_2D = "2D";                 // Marriage announcement day
	public static final String F_2L = "2L";                 // Marriage announcement location
	public static final String F_2M = "2M";                 // Marriage announcement month
	public static final String F_2Y = "2Y";                 // Marriage announcement year
	public static final String F_3C = "3C";                 // Marriage announcement code municipality
	public static final String F_3D = "3D";                 // Marriage announcement day
	public static final String F_3L = "3L";                 // Marriage announcement location
	public static final String F_3M = "3M";                 // Marriage announcement month
	public static final String F_3Y = "3Y";                 // Marriage announcement year
	public static final String F_4C = "4C";                 // Marriage announcement code municipality
	public static final String F_4D = "4D";                 // Marriage announcement day
	public static final String F_4L = "4L";                 // Marriage announcement location
	public static final String F_4M = "4M";                 // Marriage announcement month
	public static final String F_4Y = "4Y";                 // Marriage announcement year
	public static final String F_5C = "5C";                 // Marriage announcement code municipality
	public static final String F_5D = "5D";                 // Marriage announcement day
	public static final String F_5L = "5L";                 // Marriage announcement location
	public static final String F_5M = "5M";                 // Marriage announcement month
	public static final String F_5Y = "5Y";                 // Marriage announcement year
	public static final String F_6C = "6C";                 // Marriage announcement code municipality
	public static final String F_6D = "6D";                 // Marriage announcement day
	public static final String F_6L = "6L";                 // Marriage announcement location
	public static final String F_6M = "6M";                 // Marriage announcement month
	public static final String F_6Y = "6Y";                 // Marriage announcement year
	public static final String F_7C = "7C";                 // Marriage announcement code municipality
	public static final String F_7D = "7D";                 // Marriage announcement day
	public static final String F_7L = "7L";                 // Marriage announcement location
	public static final String F_7M = "7M";                 // Marriage announcement month
	public static final String F_7Y = "7Y";                 // Marriage announcement year
	public static final String F_8C = "8C";                 // Marriage announcement code municipality
	public static final String F_8D = "8D";                 // Marriage announcement day
	public static final String F_8L = "8L";                 // Marriage announcement location
	public static final String F_8M = "8M";                 // Marriage announcement month
	public static final String F_8Y = "8Y";                 // Marriage announcement year
	public static final String R_BF = "BF";                 // Father of bride (M)
	public static final String R_BM = "BM";                 // Mother of bride (M)
	public static final String R_BR = "BR";                 // Bride (M)
	public static final String R_C_ = "C_";                 // Former child (M)
	public static final String R_FA = "FA";                 // Father
	public static final String R_GF = "GF";                 // Father of Groom (M)
	public static final String R_GM = "GM";                 // Mother of Groom (M)
	public static final String R_GR = "GR";                 // Groom (M)
	public static final String R_I_ = "I_";                 // Informer (max. 4)
	public static final String R_IN = "IN";                 // Informer (max. 1 besides father)
	public static final String R_MO = "MO";                 // Mother
	public static final String R_R_ = "R_";                 // Marriage data key parts
	public static final String R_RP = "RP";                 // Research person
	public static final String R_S_ = "S_";                 // Spouse
	public static final String R_SD = "SD";                 // Source data
	public static final String R_SU = "SU";
	public static final String R_U_ = "U_";
	public static final String R_W_ = "W_";                 // Witness

	// Field name positions 5 and 6 : field description
	public static final String F_AD = "AD";                 // Age in days
	public static final String F_AF = "AF";                 // Affidavit, = akte van bekendheid (indien geen geb.cert)
	public static final String F_AM = "AM";                 // Age in months
	public static final String F_AP = "AP";                 // Attestation of poverty?
	public static final String F_AW = "AW";                 // Age in weeks
	public static final String F_AY = "AY";                 // Age in years
	public static final String F_BB = "BB";                 // Birth certificates? (M)
	public static final String F_BC = "BC";                 // Birth place code
	public static final String F_BD = "BD";                 // Day of birth
	public static final String F_BH = "BH";                 // Hour of birth
	public static final String F_BI = "BI";                 // Minute of birth
	public static final String F_BL = "BL";                 // Birth place
	public static final String F_BM = "BM";                 // Month of birth
	public static final String F_BY = "BY";                 // Year of birth
	public static final String F_CA = "CA";                 // Still alive?
	public static final String F_CC = "CC";                 // Code of the municipality
	public static final String F_CD = "CD";                 // Certificate day
	public static final String F_CE = "CE";                 // Certificate is extraction?
	public static final String F_CF = "CF";                 // Father known in certificate?
	public static final String F_CH = "CH";                 // Certificate hour
	public static final String F_CI = "CI";                 // Certificate minute
	public static final String F_CL = "CL";                 // Certificate location
	public static final String F_CM = "CM";                 // Certificate month
	public static final String F_CN = "CN";                 // Certificate number
	public static final String F_CS = "CS";                 // Civil status
	public static final String F_CT = "CT";                 // Certificate type
	public static final String F_CY = "CY";                 // Certificate year
	public static final String F_DD = "DD";                 // Day of death
	public static final String F_DE = "DE";                 // Death certificate former spouses?
	public static final String F_DH = "DH";                 // Hour of death
	public static final String F_DI = "DI";                 // Minute of death (??)
	public static final String F_DL = "DL";                 // Location of death
	public static final String F_DM = "DM";                 // Month of death
	public static final String F_DN = "DI";                 // Minute of death (??)
	public static final String F_DP = "DP";                 // Death certificates parents?
	//public static final String F_DR = "DR";                 // Relationship direction (witness) m, v, b, o
	//public static final String F_DS = "DS";                 // Relationship description (witness)
	public static final String F_DY = "DY";                 // Year of death
	public static final String F_ED = "ED";                 // Day of commencing divorce
	public static final String F_EL = "EL";                 // Location of commencing divorce
	public static final String F_EM = "EM";                 // Month of commencing divorce
	public static final String F_EY = "EY";                 // Year of commencing divorce
	public static final String F_FA = "FA";                 // Is father?
	public static final String F_FD = "FD";                 // Day of recognition by father (M5)
	public static final String F_FL = "FL";                 // Location of recognition by father (M5)
	public static final String F_FM = "FM";                 // Month of recognition by father (M5)
	public static final String F_FN = "FN";                 // First Name
	public static final String F_FY = "FY";                 // Year of recognition by father (M5)
	public static final String F_GN = "GN";                 // Gender
	public static final String F_HC = "HC";                 // Sample municipality code (B0, B6)
	public static final String F_HD = "HD";                 // Sample cohort (B0)
	public static final String F_HE = "HE";                 // Sample subcohort (B0)
	public static final String F_HG = "HG";                 // Goal of sampling (B0)
	public static final String F_HN = "HN";                 // Sample number (B0, B6)
	public static final String F_HP = "HP";                 // Province (B0)
	public static final String F_HR = "HR";                 // Region (B0)
	public static final String F_HY = "HY";                 // Sample year (B0, B6)
	public static final String F_HZ = "HZ";                 // Reason no data entry (B6)
	public static final String F_LI = "LI";                 // Limited Input (B1)
	public static final String F_LL = "LL";                 // Location (Address)
	public static final String F_LN = "LN";                 // Last Name
	public static final String F_LR = "LR";                 // Relationship direction (m, v, b, o)
	public static final String F_LS = "LS";                 // Relationship description (T50)
	public static final String F_MC = "MC";                 // Marriage count, marriages per IDNR (M0)
	public static final String F_MD = "MD";                 // Day of marriage
	public static final String F_MH = "MH";                 // Hour of marriage
	public static final String F_MI = "MI";                 // Miscellaneous information
	public static final String F_ML = "ML";                 // Location of marriage
	public static final String F_MM = "MM";                 // Month of marriage
	public static final String F_MY = "MY";                 // Year of marriage
	public static final String F_MP = "MP";                 // Permission for marriage?
	public static final String F_NM = "NM";                 // Certificate national militia?
	public static final String F_OC = "OC";                 // Occupation / profession
	public static final String F_OD = "OD";                 // Day of recognition by mother (M5)
	public static final String F_OL = "OL";                 // Location of recognition by mother (M5)
	public static final String F_OM = "OM";                 // Month of recognition by mother (M5)
	public static final String F_OY = "OY";                 // Year of recognition by mother (M5)
	public static final String F_PA = "PA";                 // Patronime
	public static final String F_PC = "PC";                 // Permission commander?
	public static final String F_PF = "PF";                 // Prefix
	public static final String F_PG = "PG";                 // Permission guardians?
	public static final String F_PN = "PN";                 // Certificate notary?
	public static final String F_LF = "PL";                 // Former Location (Address)
	public static final String F_LO = "QL";                 // Other former locations (addresses)
	public static final String F_RD = "RD";                 // Day of royal decree
	public static final String F_RM = "RM";                 // Month of royal decree
	public static final String F_RN = "RN";                 // Number of royal decree in publication (Staatsblad)
	public static final String F_RR = "RR";                 // Former child recognized?
	public static final String F_RS = "RS";                 // Number of royal decree (KM)
	public static final String F_RW = "RW";                 // Recognized by whom?
	public static final String F_RY = "RY";                 // Year of royal decree
	public static final String F_SD = "SD";                 // Day of divorce
	public static final String F_SE = "SE";                 // Marriage --> Divorce ?
	public static final String F_SG = "SG";                 // Signature
	public static final String F_SL = "SL";                 // Location of divorce
	public static final String F_SM = "SM";                 // Month of divorce
	public static final String F_SQ = "SQ";                 // Serial quantity
	public static final String F_SR = "SR";                 // Reason of divorce (1, 2 or 3)
	public static final String F_SY = "SY";                 // Year of divorce
	public static final String F_TT = "TT";                 // Title
	public static final String F_UC = "UC";
	public static final String F_UD = "UD";
	public static final String F_UL = "UL";
	public static final String F_UM = "UM";
	public static final String F_UY = "UY";

	// Field name position 7 and 8 : classification system
	public static final String C_A1 = "A1";
	public static final String C_A2 = "A2";
	public static final String C_A3 = "A3";
	public static final String C_A4 = "A4";
	public static final String C_A5 = "A5";
	public static final String C_A6 = "A6";
	public static final String C_A7 = "A7";
	public static final String C_A8 = "A8";
	public static final String C_BK = "BK";
	public static final String C_BT = "BT";
	public static final String C_CB = "CB";
	public static final String C_GA = "GA";
	public static final String C_HB = "HB";
	public static final String C_PL = "PL";
	public static final String C_PR = "PR";
	public static final String C_PN = "PN";
	public static final String C_RE = "RE";
	public static final String C_RN = "RN";
	public static final String C_TU = "TU";
	public static final String C_WA = "WA";
	public static final String C_XX = "XX";
	public static final String C_YY = "YY";

	// Error codes
	public static int E_SPB1SDCC = 0;               //steekproef_l
	public static int E_SPB1SDCY = 1;
	public static int E_SPB1SDCN = 2;
	//public static int E_SP[idnr] = ;
	//public static int E_SP[idnr] = ;
	public static int E_SPB6SUHC = 5;
	public static int E_SPB6SUHY = 6;
	public static int E_SPB6SUHN = 7;
	//public static int E_SP[idnr] = ;
	//public static int E_SP[idnr] = ;
	//public static int E_SPD1SDCC; D1RPBC;  B0SUHC = ;
	//public static int E_SP[idnr] = ;
	public static int E_DUB1IDNR = 0;               //dubbel_l
	public static int E_DUB6IDNR = 1;
	public static int E_DUD1IDNR = 2;
	public static int E_DUB2IDVL = 3;               
	public static int E_DUB3IDBY = 4;               
	public static int E_DUB4IDKA = 5;               
	public static int E_DUB5IDNR = 6;               
	public static int E_DUM1KEY  = 7;               
	public static int E_DUM2KEY  = 8;               
	public static int E_DUM3KEY  = 9;               
	public static int E_DUM4KEY  = 10;               
	public static int E_DUM5KEY  = 11;               
	public static int E_DUM6KEY  = 12;               
	public static int E_DUD2IDVL = 13;               
	public static int E_DUD3IDVL = 14;               
	public static int E_DUD4IDBY = 15;               
	public static int E_AKB1IDNR = 0;               //akte_l
	public static int E_IDB2IDNR = 0;               //idnr_l
	public static int E_IDB3IDNR = 1;
	public static int E_IDB4IDNR = 2;
	public static int E_IDB5IDNR = 3;
	public static int E_IDD2IDNR = 4;
	public static int E_IDD3IDNR = 5;
	public static int E_IDD4IDNR = 6;
	public static int E_IDM2IDNR = 7;
	public static int E_IDM3IDNR = 8;
	public static int E_IDM4IDNR = 9;
	public static int E_IDM5IDNR = 10;
	public static int E_IDM6IDNR = 11;
	public static int E_IDB12IDN = 12;
	public static int E_IDB15IDN = 13;
	public static int E_IDD13IDN = 14;
	public static int E_IDM12IDN = 15;
	public static int E_IDM14IDN = 16;
	public static int E_DLB1B1BC = 0;               //datum_l
	public static int E_DLD1D1DC = 1;
	public static int E_DLB1D1BD = 2;
	public static int E_DLB1M1BM = 3;
	public static int E_DLM1D1MD = 4;
	public static int E_DLM1M1MS = 5;
	public static int E_DLM1M1SE = 6;
	public static int E_DLM2M2AM = 7;
	public static int E_DLM5M5BM = 8;
	public static int E_DLM5M5FM = 9;
	public static int E_DLM5M5OM = 10;
	public static int E_DLM5M5BF = 11;
	public static int E_DLM5M5BO = 12;
	public static int E_ALD1RPAY = 0;               //leeftijd_l
	public static int E_ALM1RPAY = 1;
	public static int E_GLD1RPGN = 0;               //geslacht_l
	public static int E_GLM1RPGN = 1;
	public static int E_GLM3RPGN = 4;
	public static int E_DAB1SDCY = 0;               //datum_f
	public static int E_DAB1RPBY = 1;
	public static int E_DAB4SDCY = 2;
	public static int E_DAB4SDRY = 3;
	public static int E_DAB4SDMY = 4;
	public static int E_DAB5FASY = 5;
	public static int E_DAB5FADY = 6;
	public static int E_DAD1SDCY = 7;
	public static int E_DAD1RPDY = 8;
	public static int E_DAM1SDMY = 9;
	public static int E_DAM1SDSY = 10;
	public static int E_DAM1SDEY = 11;
	public static int E_DAM2SDMY = 12;
	public static int E_DAM2SAMY = 13;
	public static int E_DAM3SDMY = 14;
	public static int E_DAM4SDMY = 15;
	public static int E_DAM5SDMY = 16;
	public static int E_DAM5C_OY = 17;
	public static int E_DAM5C_FY = 18;
	public static int E_DAM5C_BY = 20;
	public static int E_DAM6SDMY = 21;
	public static int E_DAM2SD1Y = 22;
	public static int E_DAM2SD2Y = 23;
	public static int E_DAM2SD3Y = 24;
	public static int E_DAM2SD4Y = 25;
	public static int E_DAM2SD5Y = 26;
	public static int E_DAM2SD6Y = 27;
	public static int E_DAM2SD7Y = 28;
	public static int E_DAM2SD8Y = 29;
	public static int E_VAB1INLN = 0;               //vlsachternaam_f
	public static int E_VAB1MOLN = 1;
	public static int E_VAB1RPLN = 2;
	public static int E_VAB2W_LN = 3;
	public static int E_VAB4FALN = 4;
	public static int E_VAB4RPLN = 5;
	public static int E_VAB5FALN = 6;
	public static int E_VAD1RPLN = 7;
	public static int E_VAD1FALN = 8;
	public static int E_VAD1MOLN = 9;
	public static int E_VAD2S_LN = 10;
	public static int E_VAD3I_LN = 11;
	public static int E_VAM1GRLN = 12;
	public static int E_VAM1BRLN = 13;
	public static int E_VAM1GFLN = 14;
	public static int E_VAM1GMLN = 15;
	public static int E_VAM1BFLN = 16;
	public static int E_VAM1BMLN = 17;
	public static int E_VAM3S_LN = 18;
	public static int E_VAM4W_LN = 19;
	public static int E_VAM5C_LN = 20;
	public static int E_VLB1INLL = 0;              //vlslocatie_f
	public static int E_VLB1RPLL = 1;
	public static int E_VLB1MOLL = 2;
	public static int E_VLB2W_LL = 3;
	public static int E_VLB5FALL = 4;
	public static int E_VLD1RPLL = 5;
	public static int E_VLD1RPDL = 6;
	public static int E_VLD1FALL = 7;
	public static int E_VLD1MOLL = 8;
	public static int E_VLD2S_LL = 9;
	public static int E_VLD3I_LL = 10;
	public static int E_VLM1GRLL = 11;
	public static int E_VLM1BRLL = 12;
	public static int E_VLM1GRLF = 13;
	public static int E_VLM1BRLF = 14;
	public static int E_VLM1GRLO = 15;
	public static int E_VLM1BRLO = 16;
	public static int E_VLM1GFLL = 17;
	public static int E_VLM1GFDL = 18;
	public static int E_VLM1GMLL = 19;
	public static int E_VLM1GMDL = 20;
	public static int E_VLM1BFLL = 21;
	public static int E_VLM1BFDL = 22;
	public static int E_VLM1BMLL = 23;
	public static int E_VLM1BMDL = 24;
	public static int E_VLM4W_LL = 25;
	public static int E_VLB5FASL = 26;
	public static int E_VLB5FADL = 27;
	public static int E_VLB4SDML = 28;
	public static int E_VLD1SDCL = 29;
	public static int E_VLD1RPBL = 30;
	public static int E_VLM1SDML = 31;
	public static int E_VLM1SDSL = 32;
	public static int E_VLM1GRBL = 33;
	public static int E_VLM1BRBL = 34;
	public static int E_VLM2U_UL = 35;
	public static int E_VLM5C_BL = 36;
	public static int E_VLM5C_OL = 37;
	public static int E_VLM5C_FL = 38;
	public static int E_LEB1INFN = 0;               //leeg_f
	public static int E_LEB1MOFN = 1;
	public static int E_LEB1RPFN = 2;
	public static int E_LEB1INLN = 3;
	public static int E_LEB1MOLN = 4;
	public static int E_LEB1RPLN = 5;
	public static int E_LEB1INOC = 6;
	public static int E_LEB1MOOC = 7;
	public static int E_LEB2W_LN = 8;
	public static int E_LEB2W_FN = 9;
	public static int E_LEB2W_OC = 10;
	public static int E_LEB4FALN = 11;
	public static int E_LEB4FAFN = 12;
	public static int E_LEB4RPLN = 13;
	public static int E_LEB4RPFN = 14;
	public static int E_LEB5FALN = 15;
	public static int E_LEB5FAFN = 16;
	public static int E_LEB5FAOC = 17;
	//public static int E_LED1SDCL = 18; 
	//public static int E_LED1RPBL = 19;
	//public static int E_LED1RPDL = 20;
	public static int E_LED1RPLN = 21;
	public static int E_LED1RPFN = 22;
	public static int E_LED1RPOC = 23;
	public static int E_LED1FALN = 24;
	public static int E_LED1FAFN = 25;
	public static int E_LED1MOLN = 26;
	public static int E_LED1MOFN = 27;
	public static int E_LED2S_LN = 28;
	public static int E_LED2S_FN = 29;
	public static int E_LED2S_OC = 30;
	public static int E_LED3I_LN = 31;
	public static int E_LED3I_FN = 32;
	public static int E_LED3I_OC = 33;
	public static int E_LED1SDCC = 34; 
	public static int E_LED1RPCC = 35; 
	public static int E_LEM1SDML = 36;
	public static int E_LEM1GRLN = 37;
	public static int E_LEM1BRLN = 38;
	public static int E_LEM1GFLN = 39;
	public static int E_LEM1GMLN = 40;
	public static int E_LEM1BFLN = 41;
	public static int E_LEM1BMLN = 42;
	public static int E_LEM1GRFN = 43;
	public static int E_LEM1BRFN = 44;
	public static int E_LEM1GFFN = 45;
	public static int E_LEM1GMFN = 46;
	public static int E_LEM1BFFN = 47;
	public static int E_LEM1BMFN = 48;
	public static int E_LEM1GROC = 49;
	public static int E_LEM1BROC = 50;
	public static int E_LEM1GRBL = 51;
	public static int E_LEM1BRBL = 52;
	public static int E_LEM1GRLL = 53;
	public static int E_LEM1BRLL = 54;
	public static int E_LEM2U_UL = 55;
	public static int E_LEM3S_FN = 56;
	public static int E_LEM3S_LN = 57;
	public static int E_LEM4W_FN = 58;
	public static int E_LEM4W_LN = 59;
	public static int E_LEM4W_OC = 60;
	public static int E_LEM4W_LL = 61;
	public static int E_LEM5C_LN = 62;
	public static int E_LEM5C_FN = 63;
	public static int E_LEM5C_BL = 64;
	public static int E_LEM5C_OL = 65;
	public static int E_LEM5C_FL = 66;
	public static int E_HRB1SDCH = 0;               //uur_f
	public static int E_HRB1RPBH = 1;
	public static int E_HRB1SDC2 = 2;
	public static int E_HRD1SDCH = 3;
	public static int E_HRD1SDC2 = 4;
	public static int E_HRD1RPDH = 5;
	public static int E_HRM1SDMH = 7;
	public static int E_HRM1SDM2 = 8;
	public static int E_MIB1RPBI = 0;               //minuut_f
	public static int E_MID1SDCI = 1;
	public static int E_MID1RPDI = 2;
	public static int E_AGB1INAY = 0;               //leeftijd_f
	public static int E_AGB1MOAY = 1;
	public static int E_AGB2W_AY = 2;
	public static int E_AGB5FAAY = 3;
	public static int E_AGD1RPAY = 4;
	public static int E_AGD1FAAY = 5;
	public static int E_AGD1MOAY = 6;
	public static int E_AGD2S_AY = 7;
	public static int E_AGD3I_AY = 8;
	public static int E_AGM1GRAY = 9;
	public static int E_AGM1BRAY = 10;
	public static int E_AGM1GFAY = 11;
	public static int E_AGM1GMAY = 12;
	public static int E_AGM1BFAY = 13;
	public static int E_AGM1BMAY = 14;
	public static int E_AGM4W_AY = 15;
	public static int E_SGB1INSG = 0;               //handtekening_f
	public static int E_SGB2W_SG = 1;
	public static int E_SGD1INSG = 2;
	public static int E_SGD3I_SG = 3;
	public static int E_SGM1GRSG = 4;
	public static int E_SGM1BRSG = 5;
	public static int E_SGM1GFSG = 6;
	public static int E_SGM1GMSG = 7;
	public static int E_SGM1BFSG = 8;
	public static int E_SGM1BMSG = 9;
	public static int E_SGM4W_SG = 10;
	public static int E_GNB1RPGN = 0;               //geslacht_f
	public static int E_GNB4RPGN = 1;
	public static int E_GND1RPGN = 2;
	public static int E_GNM1RPGN = 3;
	public static int E_GNM3RPGN = 4;
	public static int E_GNM5C_GN = 5;
	public static int E_CSB1MOCS = 0;               //burgst_f
	public static int E_CSD1RPCS = 1;
	public static int E_CSM1GRCS = 2;
	public static int E_CSM1BRCS = 3;
	public static int E_X3B1INLL = 0;               //driedubbel_f
	public static int E_X3B1RPLL = 1;
	public static int E_X3B1MOLL = 2;
	public static int E_X3B2W_LL = 3;
	public static int E_X3B5FALL = 4;
	public static int E_X3D1RPLL = 5;
	public static int E_X3D1RPDL = 6;
	public static int E_X3D1FALL = 7;
	public static int E_X3D1MOLL = 8;
	public static int E_X3D2S_LL = 9;
	public static int E_X3D3I_LL = 10;
	public static int E_X3M1GRLL = 11;
	//public static int E_X3M1GRDL = 12;
	public static int E_X3M1BRLL = 13;
	//public static int E_X3M1BRDL = 14;
	public static int E_X3M1GRLF = 15;
	public static int E_X3M1BRLF = 16;
	public static int E_X3M1GRLO = 17;
	public static int E_X3M1BRLO = 18;
	public static int E_X3M1GFLL = 19;
	public static int E_X3M1GFDL = 20;
	public static int E_X3M1GMLL = 21;
	public static int E_X3M1GMDL = 22;
	public static int E_X3M1BFLL = 23;
	public static int E_X3M1BFDL = 24;
	public static int E_X3M1BMLL = 25;
	public static int E_X3M1BMDL = 26;
	public static int E_X3M4W_LL = 27;
	public static int E_X3B5FASL = 28;
	public static int E_X3B5FADL = 29;
	public static int E_IMB1INLL = 0;               //idem_f
	public static int E_IMB1RPLL = 1;
	public static int E_IMB1MOLL = 2;
	public static int E_IMB2W_LL = 3;
	public static int E_IMB5FALL = 4;
	public static int E_IMD1RPLL = 5;
	public static int E_IMD1RPDL = 6;
	public static int E_IMD1FALL = 7;
	public static int E_IMD1MOLL = 8;
	public static int E_IMD2S_LL = 9;
	public static int E_IMD3I_LL = 10;
	public static int E_IMM1GRLL = 11;
	//public static int E_IMM1GRDL = 12;
	public static int E_IMM1BRLL = 13;
	//public static int E_IMM1BRDL = 14;
	public static int E_IMM1GRLF = 15;
	public static int E_IMM1BRLF = 16;
	public static int E_IMM1GRLO = 17;
	public static int E_IMM1BRLO = 18;
	public static int E_IMM1GFLL = 19;
	public static int E_IMM1GFDL = 20;
	public static int E_IMM1GMLL = 21;
	public static int E_IMM1GMDL = 22;
	public static int E_IMM1BFLL = 23;
	public static int E_IMM1BFDL = 24;
	public static int E_IMM1BMLL = 25;
	public static int E_IMM1BMDL = 26;
	public static int E_IMM4W_LL = 27;
	public static int E_IMB5FASL = 28;
	public static int E_IMB5FADL = 29;
	public static int E_SQB2W_SQ = 0;               //vlgnr_f
	public static int E_SQB3SDSQ = 1;
	public static int E_SQD2S_SQ = 2;
	public static int E_SQD3I_SQ = 3;
	public static int E_SQD4SDSQ = 4;
	public static int E_SQM2SDSQ = 7;
	public static int E_SQM3SDSQ = 8;
	public static int E_SQM4SDSQ = 9;
	public static int E_SQM5C_SQ = 10;
	public static int E_SQM6SDSQ = 11;
	public static int E_CTB4SDCT = 0;               //kanttype_f
	public static int E_HZB6SUHZ = 0;               //gebcode_f
	public static int E_HZB6SULZ = 1;
	public static int E_WIB2IDNR = 0;               //getuige_f
	public static int E_WIM4IDNR = 1;
	public static int E_WIB1IDNR = 1;               //Cor Munnik - Check with Kees
	public static int E_IFB1INFA = 0;               //informerfather_l
	public static int E_IFB1RPLN = 1;               //naamaang_l
	public static int E_IFD1INSQ = 2;               //aangever_l
	public static int E_JND1INFA = 0;               //jn_f
	public static int E_JND1FACA = 1;
	public static int E_JND1MOCA = 2;
	public static int E_JND1SDCE = 8;
	public static int E_JND2S_CA = 3;
	public static int E_JNM1GFCA = 4;
	public static int E_JNM1GMCA = 5;
	public static int E_JNM1BFCA = 6;
	public static int E_JNM1BMCA = 7;
	public static int E_JNM1SDSE = 9;
	public static int E_JNM1GFMP = 10;
	public static int E_JNM1GMMP = 11;
	public static int E_JNM1BFMP = 12;
	public static int E_JNM1BMMP = 13;
	public static int E_JNM1SDBB = 14;
	public static int E_JNM1SDDP = 15;
	public static int E_JNM1SDDE = 16;
	public static int E_JNM1SDNM = 17;
	public static int E_JNM1SDPN = 18;
	public static int E_JNM1SDAF = 19;
	public static int E_JNM1SDAP = 20;
	public static int E_JNM1SDPC = 21;
	public static int E_JNM1SDPG = 22;
	public static int E_JNM5C_RR = 23;
	public static int E_SRM3S_SR = 0;               //scheiding_f
	public static int E_LRM4W_LR = 0;               //relatie_f
	public static int E_CCD1SDCC = 0;               //codeconversie_f
	public static int E_CCD1RPBC = 1;
	public static int E_CCM2SD1C = 2;
	public static int E_CCM2SD2C = 3;
	public static int E_CCM2SD3C = 4;
	public static int E_CCM2SD4C = 5;
	public static int E_CCB1SDCC = 6;
	public static int E_CCM2SD6C = 7;
	public static int E_CCM2SD7C = 8;
	public static int E_CCM2SD8C = 9;
	public static int E_RWM5C_RW = 0;               //erkenning_f
	public static int E_COB0SUHD = 0;               //cohort_f
	public static int E_BEM2SDSQ = 0;               //tussen_f
	public static int E_NLB5FACF = 0;               //nietleeg_f
	public static int E_MPM1GFMP = 0;               //permissie_f
	public static int E_MPM1GMMP = 1;
	public static int E_MPM1BFMP = 2;
	public static int E_MPM1BMMP = 3;
	public static int E_LNB1INLN = 0;               //anaam_r
	public static int E_LNB1INPF = 1;
	public static int E_LNB1MOLN = 2;
	public static int E_LNB1MOPF = 3;
	public static int E_LNB1RPLN = 4;
	public static int E_LNB1RPPF = 5;
	public static int E_LNB2W_LN = 6;
	public static int E_LNB2W_PF = 7;
	public static int E_LNB4FALN = 8;
	public static int E_LNB4FAPF = 9;
	public static int E_LNB4RPLN = 10;
	public static int E_LNB4RPPF = 11;
	public static int E_LNB5FALN = 12;
	public static int E_LNB5FAPF = 13;
	public static int E_ONB1INLN = 14;
	public static int E_ONB1MOLN = 15;
	public static int E_ONB1RPLN = 16;
	public static int E_ONB2W_LN = 17;
	public static int E_ONB4FALN = 18;
	public static int E_ONB4RPLN = 19;
	public static int E_ONB5FALN = 20;
	public static int E_LND1RPLN = 21;
	public static int E_OND1RPLN = 22;
	public static int E_LND1RPPF = 23;
	public static int E_LND1FALN = 24;
	public static int E_OND1FALN = 25;
	public static int E_LND1FAPF = 26;
	public static int E_LND1MOLN = 27;
	public static int E_OND1MOLN = 28;
	public static int E_LND1MOPF = 29;
	public static int E_LND2S_LN = 30;
	public static int E_OND2S_LN = 31;
	public static int E_LND2S_PX = 32;
	public static int E_LND3I_LN = 33;
	public static int E_OND3I_LN = 34;
	public static int E_LND3I_PF = 35;
	public static int E_ONM1GRLN = 36;
	public static int E_LNM1GRLN = 37;
	public static int E_LNM1GRPF = 38;
	public static int E_LNM1BRLN = 39;
	public static int E_ONM1BRLN = 40;
	public static int E_LNM1BRPF = 41;
	public static int E_LNM1GFLN = 42;
	public static int E_ONM1GFLN = 43;
	public static int E_LNM1GFPF = 44;
	public static int E_LNM1GMLN = 45;
	public static int E_ONM1GMLN = 46;
	public static int E_LNM1GMPF = 47;
	public static int E_LNM1BFLN = 48;
	public static int E_ONM1BFLN = 49;
	public static int E_LNM1BFPF = 50;
	public static int E_LNM1BMLN = 51;
	public static int E_ONM1BMLN = 52;
	public static int E_LNM1BMPF = 53;
	public static int E_LNM3S_LN = 54;
	public static int E_ONM3S_LN = 55;
	public static int E_LNM3S_PF = 56;
	public static int E_LNM4W_LN = 57;
	public static int E_ONM4W_LN = 58;
	public static int E_LNM4W_PF = 59;
	public static int E_LNM5C_LN = 60;
	public static int E_ONM5C_LN = 61;
	public static int E_LNM5C_PF = 62;
	
//	public static int E_PFB1MOPF = 63;             
//	public static int E_PFB1RPPF = 64;
//	public static int E_PFB2W_PF = 65;
//	public static int E_PFB1INPF = 66;
//	public static int E_PFB4FAPF = 67;
//	public static int E_PFB4RPPF = 68;
	
//	public static int E_PFB5FAPF = 69;
//	public static int E_ONM3S_PF = 70;
//	public static int E_PFM4W_PF = 71;
//	public static int E_PFM5C_PF = 72;
//	public static int E_PFD1RPPF = 73; 
//	public static int E_PFD1FAPF = 74;
//	public static int E_PFD1MOPF = 75;
//	public static int E_FND2S_PF = 76;
//	public static int E_FND3I_PF = 77;
	

	
	
	
	public static int E_FNB1INFN = 0;               //vnaam_r
	public static int E_FNB1MOFN = 1;
	public static int E_FNB1RPFN = 2;
	public static int E_FNB2W_FN = 3;
	public static int E_FNB4FAFN = 4;
	public static int E_FNB4RPFN = 5;
	public static int E_FNB5FAFN = 6;
	public static int E_FND1RPFN = 7;
	public static int E_FND1FAFN = 8;
	public static int E_FND1MOFN = 9;
	public static int E_FND2S_FN = 10;
	public static int E_FND3I_FN = 11;
	public static int E_FNM1GRFN = 12;
	public static int E_FNM1BRFN = 13;
	public static int E_FNM1GFFN = 14;
	public static int E_FNM1GMFN = 15;
	public static int E_FNM1BFFN = 16;
	public static int E_FNM1BMFN = 17;
	public static int E_FNM3S_FN = 18;
	public static int E_FNM4W_FN = 19;
	public static int E_FNM5C_FN = 20;
	public static int E_OCB1INOC = 0;               //beroep_r
	public static int E_OCB1MOOC = 1;
	public static int E_OCB5FAOC = 2;
	public static int E_OCD1RPOC = 3;
	public static int E_OCD1FAOC = 4;
	public static int E_OCD1MOOC = 5;
	public static int E_OCD2S_OC = 6;
	public static int E_OCD3I_OC = 7;
	public static int E_OCM1BROC = 8;
	public static int E_OCM1GROC = 9;
	public static int E_OCM1GFOC = 10;
	public static int E_OCM1GMOC = 11;
	public static int E_OCM1BFOC = 12;
	public static int E_OCM1BMOC = 13;
	public static int E_OCM4W_OC = 14;
	public static int E_LOB4SDML = 0;               //gemeente_r
	public static int E_LOB1INLL = 3;
	public static int E_LOB1RPLL = 4;
	public static int E_LOB1MOLL = 5;
	public static int E_LOB2W_LL = 6;
	public static int E_LOB5FALL = 7;
	public static int E_LOB5FASL = 8;
	public static int E_LOB5FADL = 9;
	public static int E_LOD1SDCL = 10;
	public static int E_LOD1RPBL = 11;
	public static int E_LOD1RPDL = 12;
	public static int E_LOM1SDML = 13;
	public static int E_LOM1SDSL = 14;
	public static int E_LOM1SDEL = 15;
	public static int E_LOM1GRBL = 16;
	public static int E_LOM1BRBL = 17;
	public static int E_LOM2U_UL = 18;
	public static int E_LOM5C_BL = 19;
	public static int E_LOM5C_OL = 20;
	public static int E_LOM5C_FL = 21;
	public static int E_LOM2SD1L = 22;
	public static int E_LOM2SD2L = 23;
	public static int E_LOM2SD3L = 24;
	public static int E_LOM2SD4L = 25;
	public static int E_LOM2SD5L = 26;
	public static int E_LOM2SD6L = 27;
	public static int E_LOM2SD7L = 28;
	public static int E_LOM2SD8L = 29;
	
	
	
	public static int E_RED3I_LS = 0;

}